const db=require('../config/database');
async function getDashboard(userId){
  const monthStart=new Date();monthStart.setDate(1);const y=monthStart.getFullYear();const m=String(monthStart.getMonth()+1).padStart(2,'0');const start=`${y}-${m}-01`;const next=new Date(y,monthStart.getMonth()+1,1);const end=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-01`;
  const [userRows]=await db.query('SELECT id,username,email,balance,currency FROM users WHERE id=?',[userId]);
  if(!userRows.length) throw Object.assign(new Error('User not found'),{status:404});
  const [summaryRows]=await db.query(`SELECT COALESCE(SUM(CASE WHEN LOWER(category)='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN LOWER(category)<>'income' THEN amount ELSE 0 END),0) expenses,COUNT(*) transactions FROM expenses WHERE user_id=?`,[userId]);
  const [monthRows]=await db.query(`SELECT COALESCE(SUM(CASE WHEN LOWER(category)='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN LOWER(category)<>'income' THEN amount ELSE 0 END),0) expenses FROM expenses WHERE user_id=? AND date>=? AND date<?`,[userId,start,end]);
  const [cats]=await db.query(`SELECT category,COALESCE(SUM(amount),0) amount FROM expenses WHERE user_id=? AND LOWER(category)<>'income' AND date>=? AND date<? GROUP BY category ORDER BY amount DESC LIMIT 6`,[userId,start,end]);
  const [recent]=await db.query('SELECT id,description,amount,category,date FROM expenses WHERE user_id=? ORDER BY date DESC,id DESC LIMIT 7',[userId]);
  const [goals]=await db.query(`SELECT id,name,target_amount,current_amount,deadline,status FROM goals WHERE user_id=? AND status<>'archived' ORDER BY status='completed',deadline IS NULL,deadline ASC LIMIT 4`,[userId]);
  const [budgets]=await db.query(`SELECT b.id,b.category,b.limit_amount,COALESCE(x.spent,0) spent FROM budgets b LEFT JOIN (SELECT category,COALESCE(SUM(amount),0) spent FROM expenses WHERE user_id=? AND LOWER(category)<>'income' AND date>=? AND date<? GROUP BY category) x ON LOWER(x.category)=LOWER(b.category) WHERE b.user_id=? AND b.month_start=? ORDER BY (COALESCE(x.spent,0)/NULLIF(b.limit_amount,0)) DESC`,[userId,start,end,userId,start]);
  const [months]=await db.query(`SELECT DATE_FORMAT(date,'%Y-%m') month,COALESCE(SUM(CASE WHEN LOWER(category)='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN LOWER(category)<>'income' THEN amount ELSE 0 END),0) expenses FROM expenses WHERE user_id=? AND date>=DATE_FORMAT(DATE_SUB(CURRENT_DATE,INTERVAL 5 MONTH),'%Y-%m-01') GROUP BY month ORDER BY month`,[userId]);
  const totalBudget=budgets.reduce((a,b)=>a+Number(b.limit_amount||0),0);const spentBudget=budgets.reduce((a,b)=>a+Number(b.spent||0),0);const monthIncome=Number(monthRows[0].income),monthExpenses=Number(monthRows[0].expenses);
  return {user:userRows[0],summary:{income:Number(summaryRows[0].income),expenses:Number(summaryRows[0].expenses),transactions:Number(summaryRows[0].transactions),net:Number(summaryRows[0].income)-Number(summaryRows[0].expenses)},month:{income:monthIncome,expenses:monthExpenses,net:monthIncome-monthExpenses},categories:cats.map(x=>({...x,amount:Number(x.amount)})),recent:recent.map(x=>({...x,amount:Number(x.amount)})),goals:goals.map(x=>({...x,target_amount:Number(x.target_amount),current_amount:Number(x.current_amount)})),budgets:budgets.map(x=>({...x,limit_amount:Number(x.limit_amount),spent:Number(x.spent),usage:Number(x.limit_amount)?Number(x.spent)/Number(x.limit_amount)*100:0})),budgetSummary:{total:totalBudget,spent:spentBudget,remaining:Math.max(totalBudget-spentBudget,0)},months:months.map(x=>({...x,income:Number(x.income),expenses:Number(x.expenses),net:Number(x.income)-Number(x.expenses)}))};
}
module.exports={getDashboard};
